# TUI Web Browser
[sic]
name = "chawan"
version = "0.0.0"
source = { type = "tarball", url = "https://github.com/sourcehut-mirrors/chawan/archive/refs/heads/main.tar.gz", hash = "sha256:d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed" }
depends = []
