# Simple, fast and user-friendly alternative to find
[sic]
name = "fd"
version = "10.4.2"
source = { type = "tarball", url = "https://github.com/sharkdp/fd/archive/refs/tags/v10.4.2.tar.gz", hash = "sha256:3a7e027af8c8e91c196ac259c703d78cd55c364706ddafbc66d02c326e57a456" }
depends = []
