# apt for fonts, the missing font manager for macOS/linux
[sic]
name = "fnt"
version = "1.9.1"
source = { type = "tarball", url = "https://github.com/alexmyczko/fnt/archive/refs/tags/1.9.1.tar.gz", hash = "sha256:d3021cbed37ae39a58e8b18ed5bdc471a12660b12e368d91270b438e58df671f" }
depends = []
