# gorae
[sic]
name = "gorae"
version = "1.2.1"
source = { type = "tarball", url = "https://github.com/Han8931/gorae/archive/refs/tags/v1.2.1.tar.gz", hash = "sha256:870e12828141eebef55a219641d26d1b736ec9d09eb82e546e13b641e51aff6c" }
depends = []
