# MapSCII is a Braille & ASCII world map renderer for your console
[sic]
name = "mapscii"
version = "0.3.1"
source = { type = "tarball", url = "https://github.com/rastapasta/mapscii/archive/refs/tags/v0.3.1.tar.gz", hash = "sha256:21c723b8ceb0d050e1e03613917aad6cb18abb43b8ba1665ae01ecfe7771b541" }
depends = []
