# Portal is a quick and easy command-line file transfer utility
[sic]
name = "portal"
version = "1.2.3"
source = { type = "tarball", url = "https://github.com/SpatiumPortae/portal/archive/refs/tags/v1.2.3.tar.gz", hash = "sha256:7a457ab1efa559b89eb5d7edbebccb1342896a42e30dbd943ffb6eea14179b36" }
depends = []
