# ripgrep - recursively search for regex patterns (Rust)
[sic]
name = "ripgrep"
version = "15.1.0"
source = { type = "tarball", url = "https://github.com/BurntSushi/ripgrep/archive/refs/tags/15.1.0.tar.gz", hash = "sha256:046fa01a216793b8bd2750f9d68d4ad43986eb9c0d6122600f993906012972e8" }
depends = []
