# Terminal based MPD client with album art support
[sic]
name = "rmpc"
version = "0.11.0"
source = { type = "tarball", url = "https://github.com/mierak/rmpc/archive/refs/tags/v0.11.0.tar.gz", hash = "sha256:930019066228d18e9530a8c0d77f10e231ab5efbbbca73b331efcd6fbb47557d" }
depends = []
