# Blazing fast terminal file manager written in Rust, based on async I/O
[sic]
name = "yazi"
version = "26.1.22"
source = { type = "tarball", url = "https://github.com/sxyazi/yazi/archive/refs/tags/v26.1.22.tar.gz", hash = "sha256:83b8a1bf166bfcb54b44b966fa3f34afa7c55584bf81d29275a1cdd99d1c9c4c" }
depends = []
